### ISSUE TITLE
Better document how to configure client tracer code

### ISSUE THREAD

**Issue by emfree** [honeycombio/honeycomb-opentracing-proxy#13]
In particular, if you're using a jaeger client with the zipkin wire format, the tracer configuration is somewhat obtuse. Need to document this clearly. Also need to document how to send a test span, debug whether ingest is working, etc.

**Comment by bdarfler** [comment]
As per the README "This project is not actively maintained and you should not use it. New issues and pull requests will likely be ignored. OpenTracing has been superseded by OpenTelementry."

We are now closing all pull requests and issues and archiving the repo.
