### ISSUE TITLE
Dynamic sampling

### ISSUE THREAD

**Issue by sj26** [honeycombio/honeycomb-opentracing-proxy#22]
Could this agent be extended to allow dynamic sampling of traces, maybe by adding a sample rate as meta-data to root spans? Would this be considered, feature-wise?

**Comment by bdarfler** [comment]
As per the README "This project is not actively maintained and you should not use it. New issues and pull requests will likely be ignored. OpenTracing has been superseded by OpenTelementry."

We are now closing all pull requests and issues and archiving the repo.
