### ISSUE TITLE
Allow configuring the Access-Control-Allow-Origin header

### ISSUE THREAD

**Issue by eanakashima** [honeycombio/honeycomb-opentracing-proxy#23]
In some cases it might be useful to send events to the proxy from a browser-based application. The browser would check CORS headers before sending, so the proxy would need to set `Access-Control-Allow-Origin` to the customer's expected origin (or something permissive like `*`). Would be nice to allow proxy users to configure the value of this header to support this use case.

**Comment by bdarfler** [comment]
As per the README "This project is not actively maintained and you should not use it. New issues and pull requests will likely be ignored. OpenTracing has been superseded by OpenTelementry."

We are now closing all pull requests and issues and archiving the repo.
