### ISSUE TITLE
Allow configuration of underlying libhoney to tune throughput

### ISSUE THREAD

**Issue by maplebed** [honeycombio/honeycomb-opentracing-proxy#24]
When processing large numbers of spans, it is possible to overflow the libhoney queue.  The default batch size of 50 is fine for low traffic, but it would be nice to be able to tune that and other libhoney parameters (number of concurrent batches, batch timeout, queue size, etc.).

Consider adding a method of configuring the underlying libhoney with all the knobs it has.

**Comment by kpruden** [comment]
I may end up needing this sooner rather than later, and I'd be willing to take a stab at contributing this, if someone can point me to the approximate place in the code where I'd need to look..

**Comment by kpruden** [comment]
Looks like here: https://github.com/honeycombio/honeycomb-opentracing-proxy/blob/master/sinks/honeycomb.go#L30

**Comment by bdarfler** [comment]
As per the README "This project is not actively maintained and you should not use it. New issues and pull requests will likely be ignored. OpenTracing has been superseded by OpenTelementry."

We are now closing all pull requests and issues and archiving the repo.
