### ISSUE TITLE
Add in some metrics reporting to a secondary dataset

### ISSUE THREAD

**Issue by maplebed** [honeycombio/honeycomb-opentracing-proxy#25]
It'd be lovely to know things like the length of the libhoney queue. Consider stealing the metrics implementation from samproxy (https://github.com/honeycombio/samproxy/tree/master/metrics) and use it to give people running the OT proxy some insight into how it's functioning.

**Comment by bdarfler** [comment]
As per the README "This project is not actively maintained and you should not use it. New issues and pull requests will likely be ignored. OpenTracing has been superseded by OpenTelementry."

We are now closing all pull requests and issues and archiving the repo.
