### ISSUE TITLE
Incoming JSON spans that omit the timestamp get assigned 1970 as a timestamp

### ISSUE THREAD

**Issue by maplebed** [honeycombio/honeycomb-opentracing-proxy#28]
If an incoming JSON span omits the timestamp field, it gets set to 0 when getting serialized into the `ZipkinJSONSpan` type. The time conversion from the expected microseconds since unix epoch then happens on that zero value, which returns 1970 as a `time.Time` object on the `Span` that will be sent to Honeycomb. 

It would be nice if there was a zero check against the timestamp to cancel the whole thing and, in the face of no incoming timestamp, either assign `now` or pass it on to Honeycomb with no timestamp (where the API will assign `now`).

**Comment by bdarfler** [comment]
As per the README "This project is not actively maintained and you should not use it. New issues and pull requests will likely be ignored. OpenTracing has been superseded by OpenTelementry."

We are now closing all pull requests and issues and archiving the repo.
