### ISSUE TITLE
Support specifying a sample rate as a probability

### ISSUE THREAD

**Issue by kpruden** [honeycombio/honeycomb-opentracing-proxy#31]
The current way of specifying a sample rate is a bit confusing (to me), and imprecise.

My understanding is `--samplerate=n` means `1/n` traces will be forwarded, and I think `n` must be an integer. This means, expressed as a probability, the **least aggressive** sample rate possible is 50% (`1/2`). Going from 100% to 50% is a big jump. I'd like to be able to specify the sample rate as a probability between 0 and 100 (or a float between 0 and 1). This would let me have a sample rate of, say, 75%.

**Comment by bdarfler** [comment]
As per the README "This project is not actively maintained and you should not use it. New issues and pull requests will likely be ignored. OpenTracing has been superseded by OpenTelementry."

We are now closing all pull requests and issues and archiving the repo.
