### ISSUE TITLE
Emit Beeline fields instead of Zipkin model fields

### ISSUE THREAD

**Issue by nathanleclaire** [honeycombio/honeycomb-opentracing-proxy#34]
Then at least theoretically you could intermingle Beelines and OT Proxy in the same dataset.

**Comment by cranti** [comment]
Are there still plans to merge the related PR? My team wants to combine traces sent through the proxy (e.g. from Envoy) with traces sent directly to Honeycomb. As far as I can tell, that isn't possible without this change.

**Comment by akvanhar** [comment]
@cranti , following up internally about this and will get back to you.

**Comment by nathanleclaire** [comment]
Hi @cranti , I had to drop it for now due to the required plumbing to support multiple Go structs to make the various tags work for the flag-based solution. We always welcome PRs from enterprising folks, it just hasn't been top of list for me to work on lately! :)

**Comment by cranti** [comment]
@nathanleclaire thanks for the update!! We're just starting to get tracing data into Honeycomb, so we're okay with the old format for now. But this is on my radar as a PR to work on if I have a lull.

**Comment by bdarfler** [comment]
As per the README "This project is not actively maintained and you should not use it. New issues and pull requests will likely be ignored. OpenTracing has been superseded by OpenTelementry."

We are now closing all pull requests and issues and archiving the repo.
