### ISSUE TITLE
[feature] accept protobuf-encoded zipkin

### ISSUE THREAD

**Issue by antifuchs** [honeycombio/honeycomb-opentracing-proxy#47]
I'm setting up the opentracing proxy for a little personal project, ingesting spans from envoy; unfortunately, the most interesting spans get dropped, because they can't be decoded due to this envoy bug: https://github.com/envoyproxy/envoy/issues/9341 (fixed in https://github.com/envoyproxy/envoy/pull/9432):

`time="2020-04-16T14:35:01Z" level=info msg="error unmarshaling spans" error="json: cannot unmarshal number 1.58704770013901e+15 into Go struct field ZipkinJSONSpan.timestamp of type int64" type=application/json`

This could ~easily be avoided by accepting a data encoding that has an unmistakable numeric representation (protobuf!) - and envoy supports sending v2 zipkin spans as protobuf in newer versions. 

Support for that would be really neat, as I imagine it'll also ~guarantee forwards-compatibility of the schema...

**Comment by bdarfler** [comment]
As per the README "This project is not actively maintained and you should not use it. New issues and pull requests will likely be ignored. OpenTracing has been superseded by OpenTelementry."

We are now closing all pull requests and issues and archiving the repo.
