### ISSUE TITLE
Handle annotations and ca/sa binary annotations

### ISSUE THREAD

**Issue by emfree** [honeycombio/honeycomb-opentracing-proxy#6]
Currently, we simply discard any annotations and client addr / server addr binary annotations on spans. In the future we could do something smarter.

**Comment by bdarfler** [comment]
As per the README "This project is not actively maintained and you should not use it. New issues and pull requests will likely be ignored. OpenTracing has been superseded by OpenTelementry."

We are now closing all pull requests and issues and archiving the repo.
