### ISSUE TITLE
Support the Zipkin V2 API

### ISSUE THREAD

**Issue by emfree** [honeycombio/honeycomb-opentracing-proxy#7]
If there is actual demand for it.

**Comment by drubin** [comment]
Currently trying to migrate opencencus implementations its a little difficult with nodejs so supporting v1 would be very helpful for languages that don't have honeycomb exporters.

**Comment by will-sargent-eero** [comment]
Currently I get big warnings say Zipkin v1 format using Thrift is deprecated and it'd be nice to stop those.
